### ISSUE TITLE
firefox-esr crashed in debian buster

### ISSUE THREAD

**Issue by utzcoz** [maruos/blueprints#12]
Hi @pdsouza , I have tried upgrade debian to buster, but I found the firefox-esr crashed in it, but firefox works fine in debian buster.  Maybe when someone wants to upgrade to buster,  he/she should be attention  to this problem.

Thanks.

**Comment by pdsouza** [comment]
Hi @utzcoz, thanks for the report. Yes there is an issue with the latest
firedox-esr on ARM devices. I believe Firefox 60+ has this issue, so you
must downgrade to the previous version (52.9.0) until it is fixed upstream
in Debian.

**Comment by pdsouza** [comment]
Here is a reference to the upstream bug for anyone affected: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909498

**Comment by pdsouza** [comment]
I explicitly marked the `firefox-esr` package as held back to prevent it from accidentally being upgraded when a user runs `apt-get upgrade`: https://github.com/maruos/blueprints/commit/04f5461efc3c73b8594db67e9258124deef47047

**Comment by utzcoz** [comment]
@pdsouza Thanks. I will use your patch to hold on `firefox-esr` to specific version and close the issue.

**Comment by pdsouza** [comment]
Looks like [#909498](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909498) is still open. Unfortunately, the current builds are breaking because Debian stretch archives no longer have `firefox-esr_52.9.0` that was being used as a workaround.

I tested the latest `firefox-esr_60.3.0` on arm64 and it works fine - but armhf still crashes. So for armhf we'll need to work around it as suggested in this [thread](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909498;msg=32) by installing the package from jessie instead.

I'm going to keep this open until this is fixed.

**Comment by pdsouza** [comment]
Deployed a workaround for armhf: https://github.com/maruos/blueprints/commit/e8cb47acb321ba30f7acd810ea5eade68f728983
